### ISSUE TITLE
Name conflict - does not build on sbcl

### ISSUE THREAD

**Issue by quicklisp** [Rudolph-Miller/dyna#38]
http://report.quicklisp.org/2016-11-08/failure-report/dyna.html#dyna has a log.

    Unhandled SB-EXT:NAME-CONFLICT in thread #<SB-THREAD:THREAD "main thread" RUNNING {1002D4F5C3}>: IMPORT LIST=-OP causes name-conflicts in #<PACKAGE "SXQL.OPERATOR"> between the following symbols:DYNA.SXQL::LIST=-OP, SXQL.OPERATOR::LIST=-OP

**Comment by Rudolph-Miller** [comment]
It can be by https://github.com/fukamachi/sxql/commit/84ab5e7c49cdb630ca7a10436ee86d7ea9562469.
I'll try to fix Dyna.
